// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package google

import "fmt"

// Provide a separate asset type constant so we don't have to worry about name conflicts between IAM and non-IAM converter files
const ActiveDirectoryDomainIAMAssetType string = "managedidentities.googleapis.com/Domain"

func resourceConverterActiveDirectoryDomainIamPolicy() ResourceConverter {
	return ResourceConverter{
		AssetType:         ActiveDirectoryDomainIAMAssetType,
		Convert:           GetActiveDirectoryDomainIamPolicyCaiObject,
		MergeCreateUpdate: MergeActiveDirectoryDomainIamPolicy,
	}
}

func resourceConverterActiveDirectoryDomainIamBinding() ResourceConverter {
	return ResourceConverter{
		AssetType:         ActiveDirectoryDomainIAMAssetType,
		Convert:           GetActiveDirectoryDomainIamBindingCaiObject,
		FetchFullResource: FetchActiveDirectoryDomainIamPolicy,
		MergeCreateUpdate: MergeActiveDirectoryDomainIamBinding,
		MergeDelete:       MergeActiveDirectoryDomainIamBindingDelete,
	}
}

func resourceConverterActiveDirectoryDomainIamMember() ResourceConverter {
	return ResourceConverter{
		AssetType:         ActiveDirectoryDomainIAMAssetType,
		Convert:           GetActiveDirectoryDomainIamMemberCaiObject,
		FetchFullResource: FetchActiveDirectoryDomainIamPolicy,
		MergeCreateUpdate: MergeActiveDirectoryDomainIamMember,
		MergeDelete:       MergeActiveDirectoryDomainIamMemberDelete,
	}
}

func GetActiveDirectoryDomainIamPolicyCaiObject(d TerraformResourceData, config *Config) ([]Asset, error) {
	return newActiveDirectoryDomainIamAsset(d, config, expandIamPolicyBindings)
}

func GetActiveDirectoryDomainIamBindingCaiObject(d TerraformResourceData, config *Config) ([]Asset, error) {
	return newActiveDirectoryDomainIamAsset(d, config, expandIamRoleBindings)
}

func GetActiveDirectoryDomainIamMemberCaiObject(d TerraformResourceData, config *Config) ([]Asset, error) {
	return newActiveDirectoryDomainIamAsset(d, config, expandIamMemberBindings)
}

func MergeActiveDirectoryDomainIamPolicy(existing, incoming Asset) Asset {
	existing.IAMPolicy = incoming.IAMPolicy
	return existing
}

func MergeActiveDirectoryDomainIamBinding(existing, incoming Asset) Asset {
	return mergeIamAssets(existing, incoming, mergeAuthoritativeBindings)
}

func MergeActiveDirectoryDomainIamBindingDelete(existing, incoming Asset) Asset {
	return mergeDeleteIamAssets(existing, incoming, mergeDeleteAuthoritativeBindings)
}

func MergeActiveDirectoryDomainIamMember(existing, incoming Asset) Asset {
	return mergeIamAssets(existing, incoming, mergeAdditiveBindings)
}

func MergeActiveDirectoryDomainIamMemberDelete(existing, incoming Asset) Asset {
	return mergeDeleteIamAssets(existing, incoming, mergeDeleteAdditiveBindings)
}

func newActiveDirectoryDomainIamAsset(
	d TerraformResourceData,
	config *Config,
	expandBindings func(d TerraformResourceData) ([]IAMBinding, error),
) ([]Asset, error) {
	bindings, err := expandBindings(d)
	if err != nil {
		return []Asset{}, fmt.Errorf("expanding bindings: %v", err)
	}

	name, err := assetName(d, config, "//managedidentities.googleapis.com/projects/{{project}}/locations/global/domains/{{domain_name}}")
	if err != nil {
		return []Asset{}, err
	}

	return []Asset{{
		Name: name,
		Type: ActiveDirectoryDomainIAMAssetType,
		IAMPolicy: &IAMPolicy{
			Bindings: bindings,
		},
	}}, nil
}

func FetchActiveDirectoryDomainIamPolicy(d TerraformResourceData, config *Config) (Asset, error) {
	// Check if the identity field returns a value
	if _, ok := d.GetOk("domain_name"); !ok {
		return Asset{}, ErrEmptyIdentityField
	}

	return fetchIamPolicy(
		ActiveDirectoryDomainIamUpdaterProducer,
		d,
		config,
		"//managedidentities.googleapis.com/projects/{{project}}/locations/global/domains/{{domain_name}}",
		ActiveDirectoryDomainIAMAssetType,
	)
}
