// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package google

import "fmt"

// Provide a separate asset type constant so we don't have to worry about name conflicts between IAM and non-IAM converter files
const BeyondcorpAppGatewayIAMAssetType string = "beyondcorp.googleapis.com/AppGateway"

func resourceConverterBeyondcorpAppGatewayIamPolicy() ResourceConverter {
	return ResourceConverter{
		AssetType:         BeyondcorpAppGatewayIAMAssetType,
		Convert:           GetBeyondcorpAppGatewayIamPolicyCaiObject,
		MergeCreateUpdate: MergeBeyondcorpAppGatewayIamPolicy,
	}
}

func resourceConverterBeyondcorpAppGatewayIamBinding() ResourceConverter {
	return ResourceConverter{
		AssetType:         BeyondcorpAppGatewayIAMAssetType,
		Convert:           GetBeyondcorpAppGatewayIamBindingCaiObject,
		FetchFullResource: FetchBeyondcorpAppGatewayIamPolicy,
		MergeCreateUpdate: MergeBeyondcorpAppGatewayIamBinding,
		MergeDelete:       MergeBeyondcorpAppGatewayIamBindingDelete,
	}
}

func resourceConverterBeyondcorpAppGatewayIamMember() ResourceConverter {
	return ResourceConverter{
		AssetType:         BeyondcorpAppGatewayIAMAssetType,
		Convert:           GetBeyondcorpAppGatewayIamMemberCaiObject,
		FetchFullResource: FetchBeyondcorpAppGatewayIamPolicy,
		MergeCreateUpdate: MergeBeyondcorpAppGatewayIamMember,
		MergeDelete:       MergeBeyondcorpAppGatewayIamMemberDelete,
	}
}

func GetBeyondcorpAppGatewayIamPolicyCaiObject(d TerraformResourceData, config *Config) ([]Asset, error) {
	return newBeyondcorpAppGatewayIamAsset(d, config, expandIamPolicyBindings)
}

func GetBeyondcorpAppGatewayIamBindingCaiObject(d TerraformResourceData, config *Config) ([]Asset, error) {
	return newBeyondcorpAppGatewayIamAsset(d, config, expandIamRoleBindings)
}

func GetBeyondcorpAppGatewayIamMemberCaiObject(d TerraformResourceData, config *Config) ([]Asset, error) {
	return newBeyondcorpAppGatewayIamAsset(d, config, expandIamMemberBindings)
}

func MergeBeyondcorpAppGatewayIamPolicy(existing, incoming Asset) Asset {
	existing.IAMPolicy = incoming.IAMPolicy
	return existing
}

func MergeBeyondcorpAppGatewayIamBinding(existing, incoming Asset) Asset {
	return mergeIamAssets(existing, incoming, mergeAuthoritativeBindings)
}

func MergeBeyondcorpAppGatewayIamBindingDelete(existing, incoming Asset) Asset {
	return mergeDeleteIamAssets(existing, incoming, mergeDeleteAuthoritativeBindings)
}

func MergeBeyondcorpAppGatewayIamMember(existing, incoming Asset) Asset {
	return mergeIamAssets(existing, incoming, mergeAdditiveBindings)
}

func MergeBeyondcorpAppGatewayIamMemberDelete(existing, incoming Asset) Asset {
	return mergeDeleteIamAssets(existing, incoming, mergeDeleteAdditiveBindings)
}

func newBeyondcorpAppGatewayIamAsset(
	d TerraformResourceData,
	config *Config,
	expandBindings func(d TerraformResourceData) ([]IAMBinding, error),
) ([]Asset, error) {
	bindings, err := expandBindings(d)
	if err != nil {
		return []Asset{}, fmt.Errorf("expanding bindings: %v", err)
	}

	name, err := assetName(d, config, "//beyondcorp.googleapis.com/projects/{{project}}/locations/{{region}}/appGateways/{{name}}/{{name}}")
	if err != nil {
		return []Asset{}, err
	}

	return []Asset{{
		Name: name,
		Type: BeyondcorpAppGatewayIAMAssetType,
		IAMPolicy: &IAMPolicy{
			Bindings: bindings,
		},
	}}, nil
}

func FetchBeyondcorpAppGatewayIamPolicy(d TerraformResourceData, config *Config) (Asset, error) {
	// Check if the identity field returns a value
	if _, ok := d.GetOk("region"); !ok {
		return Asset{}, ErrEmptyIdentityField
	}
	if _, ok := d.GetOk("name"); !ok {
		return Asset{}, ErrEmptyIdentityField
	}

	return fetchIamPolicy(
		BeyondcorpAppGatewayIamUpdaterProducer,
		d,
		config,
		"//beyondcorp.googleapis.com/projects/{{project}}/locations/{{region}}/appGateways/{{name}}/{{name}}",
		BeyondcorpAppGatewayIAMAssetType,
	)
}
