// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package google

import "fmt"

// Provide a separate asset type constant so we don't have to worry about name conflicts between IAM and non-IAM converter files
const BeyondcorpAppConnectorIAMAssetType string = "beyondcorp.googleapis.com/AppConnector"

func resourceConverterBeyondcorpAppConnectorIamPolicy() ResourceConverter {
	return ResourceConverter{
		AssetType:         BeyondcorpAppConnectorIAMAssetType,
		Convert:           GetBeyondcorpAppConnectorIamPolicyCaiObject,
		MergeCreateUpdate: MergeBeyondcorpAppConnectorIamPolicy,
	}
}

func resourceConverterBeyondcorpAppConnectorIamBinding() ResourceConverter {
	return ResourceConverter{
		AssetType:         BeyondcorpAppConnectorIAMAssetType,
		Convert:           GetBeyondcorpAppConnectorIamBindingCaiObject,
		FetchFullResource: FetchBeyondcorpAppConnectorIamPolicy,
		MergeCreateUpdate: MergeBeyondcorpAppConnectorIamBinding,
		MergeDelete:       MergeBeyondcorpAppConnectorIamBindingDelete,
	}
}

func resourceConverterBeyondcorpAppConnectorIamMember() ResourceConverter {
	return ResourceConverter{
		AssetType:         BeyondcorpAppConnectorIAMAssetType,
		Convert:           GetBeyondcorpAppConnectorIamMemberCaiObject,
		FetchFullResource: FetchBeyondcorpAppConnectorIamPolicy,
		MergeCreateUpdate: MergeBeyondcorpAppConnectorIamMember,
		MergeDelete:       MergeBeyondcorpAppConnectorIamMemberDelete,
	}
}

func GetBeyondcorpAppConnectorIamPolicyCaiObject(d TerraformResourceData, config *Config) ([]Asset, error) {
	return newBeyondcorpAppConnectorIamAsset(d, config, expandIamPolicyBindings)
}

func GetBeyondcorpAppConnectorIamBindingCaiObject(d TerraformResourceData, config *Config) ([]Asset, error) {
	return newBeyondcorpAppConnectorIamAsset(d, config, expandIamRoleBindings)
}

func GetBeyondcorpAppConnectorIamMemberCaiObject(d TerraformResourceData, config *Config) ([]Asset, error) {
	return newBeyondcorpAppConnectorIamAsset(d, config, expandIamMemberBindings)
}

func MergeBeyondcorpAppConnectorIamPolicy(existing, incoming Asset) Asset {
	existing.IAMPolicy = incoming.IAMPolicy
	return existing
}

func MergeBeyondcorpAppConnectorIamBinding(existing, incoming Asset) Asset {
	return mergeIamAssets(existing, incoming, mergeAuthoritativeBindings)
}

func MergeBeyondcorpAppConnectorIamBindingDelete(existing, incoming Asset) Asset {
	return mergeDeleteIamAssets(existing, incoming, mergeDeleteAuthoritativeBindings)
}

func MergeBeyondcorpAppConnectorIamMember(existing, incoming Asset) Asset {
	return mergeIamAssets(existing, incoming, mergeAdditiveBindings)
}

func MergeBeyondcorpAppConnectorIamMemberDelete(existing, incoming Asset) Asset {
	return mergeDeleteIamAssets(existing, incoming, mergeDeleteAdditiveBindings)
}

func newBeyondcorpAppConnectorIamAsset(
	d TerraformResourceData,
	config *Config,
	expandBindings func(d TerraformResourceData) ([]IAMBinding, error),
) ([]Asset, error) {
	bindings, err := expandBindings(d)
	if err != nil {
		return []Asset{}, fmt.Errorf("expanding bindings: %v", err)
	}

	name, err := assetName(d, config, "//beyondcorp.googleapis.com/projects/{{project}}/locations/{{region}}/appConnectors/{{name}}/{{name}}")
	if err != nil {
		return []Asset{}, err
	}

	return []Asset{{
		Name: name,
		Type: BeyondcorpAppConnectorIAMAssetType,
		IAMPolicy: &IAMPolicy{
			Bindings: bindings,
		},
	}}, nil
}

func FetchBeyondcorpAppConnectorIamPolicy(d TerraformResourceData, config *Config) (Asset, error) {
	// Check if the identity field returns a value
	if _, ok := d.GetOk("region"); !ok {
		return Asset{}, ErrEmptyIdentityField
	}
	if _, ok := d.GetOk("name"); !ok {
		return Asset{}, ErrEmptyIdentityField
	}

	return fetchIamPolicy(
		BeyondcorpAppConnectorIamUpdaterProducer,
		d,
		config,
		"//beyondcorp.googleapis.com/projects/{{project}}/locations/{{region}}/appConnectors/{{name}}/{{name}}",
		BeyondcorpAppConnectorIAMAssetType,
	)
}
