// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package google

import (
	"fmt"

	"github.com/hashicorp/errwrap"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"google.golang.org/api/cloudresourcemanager/v1"
)

var ActiveDirectoryDomainIamSchema = map[string]*schema.Schema{
	"project": {
		Type:     schema.TypeString,
		Computed: true,
		Optional: true,
		ForceNew: true,
	},
	"domain_name": {
		Type:             schema.TypeString,
		Required:         true,
		ForceNew:         true,
		DiffSuppressFunc: compareSelfLinkOrResourceName,
	},
}

type ActiveDirectoryDomainIamUpdater struct {
	project    string
	domainName string
	d          TerraformResourceData
	Config     *Config
}

func ActiveDirectoryDomainIamUpdaterProducer(d TerraformResourceData, config *Config) (ResourceIamUpdater, error) {
	values := make(map[string]string)

	project, _ := getProject(d, config)
	if project != "" {
		if err := d.Set("project", project); err != nil {
			return nil, fmt.Errorf("Error setting project: %s", err)
		}
	}
	values["project"] = project
	if v, ok := d.GetOk("domain_name"); ok {
		values["domain_name"] = v.(string)
	}

	// We may have gotten either a long or short name, so attempt to parse long name if possible
	m, err := getImportIdQualifiers([]string{"projects/(?P<project>[^/]+)/locations/global/domains/(?P<domain_name>[^/]+)", "(?P<project>[^/]+)/(?P<domain_name>[^/]+)", "(?P<domain_name>[^/]+)"}, d, config, d.Get("domain_name").(string))
	if err != nil {
		return nil, err
	}

	for k, v := range m {
		values[k] = v
	}

	u := &ActiveDirectoryDomainIamUpdater{
		project:    values["project"],
		domainName: values["domain_name"],
		d:          d,
		Config:     config,
	}

	if err := d.Set("project", u.project); err != nil {
		return nil, fmt.Errorf("Error setting project: %s", err)
	}
	if err := d.Set("domain_name", u.GetResourceId()); err != nil {
		return nil, fmt.Errorf("Error setting domain_name: %s", err)
	}

	return u, nil
}

func ActiveDirectoryDomainIdParseFunc(d *schema.ResourceData, config *Config) error {
	values := make(map[string]string)

	project, _ := getProject(d, config)
	if project != "" {
		values["project"] = project
	}

	m, err := getImportIdQualifiers([]string{"projects/(?P<project>[^/]+)/locations/global/domains/(?P<domain_name>[^/]+)", "(?P<project>[^/]+)/(?P<domain_name>[^/]+)", "(?P<domain_name>[^/]+)"}, d, config, d.Id())
	if err != nil {
		return err
	}

	for k, v := range m {
		values[k] = v
	}

	u := &ActiveDirectoryDomainIamUpdater{
		project:    values["project"],
		domainName: values["domain_name"],
		d:          d,
		Config:     config,
	}
	if err := d.Set("domain_name", u.GetResourceId()); err != nil {
		return fmt.Errorf("Error setting domain_name: %s", err)
	}
	d.SetId(u.GetResourceId())
	return nil
}

func (u *ActiveDirectoryDomainIamUpdater) GetResourceIamPolicy() (*cloudresourcemanager.Policy, error) {
	url, err := u.qualifyDomainUrl("getIamPolicy")
	if err != nil {
		return nil, err
	}

	project, err := getProject(u.d, u.Config)
	if err != nil {
		return nil, err
	}
	var obj map[string]interface{}

	userAgent, err := generateUserAgentString(u.d, u.Config.userAgent)
	if err != nil {
		return nil, err
	}

	policy, err := sendRequest(u.Config, "GET", project, url, userAgent, obj)
	if err != nil {
		return nil, errwrap.Wrapf(fmt.Sprintf("Error retrieving IAM policy for %s: {{err}}", u.DescribeResource()), err)
	}

	out := &cloudresourcemanager.Policy{}
	err = Convert(policy, out)
	if err != nil {
		return nil, errwrap.Wrapf("Cannot convert a policy to a resource manager policy: {{err}}", err)
	}

	return out, nil
}

func (u *ActiveDirectoryDomainIamUpdater) SetResourceIamPolicy(policy *cloudresourcemanager.Policy) error {
	json, err := ConvertToMap(policy)
	if err != nil {
		return err
	}

	obj := make(map[string]interface{})
	obj["policy"] = json

	url, err := u.qualifyDomainUrl("setIamPolicy")
	if err != nil {
		return err
	}
	project, err := getProject(u.d, u.Config)
	if err != nil {
		return err
	}

	userAgent, err := generateUserAgentString(u.d, u.Config.userAgent)
	if err != nil {
		return err
	}

	_, err = sendRequestWithTimeout(u.Config, "POST", project, url, userAgent, obj, u.d.Timeout(schema.TimeoutCreate))
	if err != nil {
		return errwrap.Wrapf(fmt.Sprintf("Error setting IAM policy for %s: {{err}}", u.DescribeResource()), err)
	}

	return nil
}

func (u *ActiveDirectoryDomainIamUpdater) qualifyDomainUrl(methodIdentifier string) (string, error) {
	urlTemplate := fmt.Sprintf("{{ActiveDirectoryBasePath}}%s:%s", fmt.Sprintf("projects/%s/locations/global/domains/%s", u.project, u.domainName), methodIdentifier)
	url, err := replaceVars(u.d, u.Config, urlTemplate)
	if err != nil {
		return "", err
	}
	return url, nil
}

func (u *ActiveDirectoryDomainIamUpdater) GetResourceId() string {
	return fmt.Sprintf("projects/%s/locations/global/domains/%s", u.project, u.domainName)
}

func (u *ActiveDirectoryDomainIamUpdater) GetMutexKey() string {
	return fmt.Sprintf("iam-activedirectory-domain-%s", u.GetResourceId())
}

func (u *ActiveDirectoryDomainIamUpdater) DescribeResource() string {
	return fmt.Sprintf("activedirectory domain %q", u.GetResourceId())
}
